Add python as an officially supported language and add links/info to readme
wpilibsuite/.github pull request #2
Opened 2023-11-26 16:24 UTC by sciencewhiz

2023-11-26 21:13 UTC, virtuald commented
FWIW, I am working on a new API site

2023-11-28 12:43 UTC, spacey-sooty requested changes

2023-11-28 12:43 UTC, spacey-sooty commented on profile/README.md
> +In general, C++ offers better high-end performance, at the cost of increased user effort (memory must be handled manually, and the C++ compiler does not do much to ensure user code will not crash at
Java and Python offer lesser performance would probably be better to read

2023-12-29 05:39 UTC, PeterJohnson approved these changes

2023-12-29 05:39 UTC, merged